import { NavLink } from 'react-router-dom'
import { ArrowRight, Zap, Shield, BarChart2, Wifi } from 'lucide-react'

const PILLARS = [
  {
    icon: Zap, color:'var(--lime)', bg:'var(--lime)',
    title:'Tokenized Energy',
    body:'Every kilowatt-hour generated by your solar panels is verified by our oracle and minted as an ERT token on the Ethereum Sepolia blockchain — giving energy a real, traceable monetary value.',
  },
  {
    icon: Shield, color:'var(--forest)', bg:'var(--forest)',
    title:'Trustless Escrow',
    body:'The Marketplace smart contract holds tokens in escrow until a buyer pays. No counterparty risk, no middlemen. Settlement is atomic — tokens and ETH swap in a single transaction.',
  },
  {
    icon: BarChart2, color:'var(--slate)', bg:'var(--ink)',
    title:'Real-time Oracle',
    body:'Our backend oracle listens to simulated "smart meter" data every 30 seconds. It automatically mints ERT when you generate surplus and burns ERT when you consume — keeping your balance accurate.',
  },
  {
    icon: Wifi, color:'var(--mantis)', bg:'var(--mantis)',
    title:'Live Event Indexer',
    body:'All Marketplace events (OrderCreated, OrderFulfilled, OrderCancelled) are indexed into MongoDB in real-time via Ethers.js listeners, powering the live socket feeds in your dashboard.',
  },
]

const STACK = [
  { cat:'Smart Contracts', items:['Solidity 0.8.20', 'ERC-20 (EnergyToken)', 'Custom Escrow (Marketplace)', 'Hardhat + Chai testing'] },
  { cat:'Backend Oracle', items:['Node.js + Express', 'Ethers.js v6', 'MongoDB Atlas (M0 free)', 'Socket.io real-time'] },
  { cat:'Frontend', items:['React 18 + Vite', 'Recharts data viz', 'MetaMask / EIP-1193', 'React Router v6'] },
  { cat:'Infrastructure', items:['Ethereum Sepolia Testnet', 'Alchemy RPC node', 'Render (backend hosting)', 'Vercel (frontend)'] },
]

export default function About() {
  return (
    <div className="page">
      <div className="wrap" style={{ paddingTop:40, paddingBottom:72 }}>

        {/* Hero */}
        <div className="fu" style={{ marginBottom:40 }}>
          <div className="section-eyebrow" style={{ marginBottom:12 }}>About GridLedger</div>
          <h1 style={{ fontSize:52, fontWeight:800, letterSpacing:'-0.04em', lineHeight:1.0, maxWidth:680, marginBottom:20 }}>
            Peer-to-peer energy trading,<br/>
            <span style={{ color:'var(--forest)' }}>powered by Ethereum.</span>
          </h1>
          <p style={{ fontSize:17, color:'var(--ink-dim)', maxWidth:600, lineHeight:1.7, marginBottom:28 }}>
            GridLedger is an open-source demonstration platform showing how blockchain technology can enable a truly decentralised energy market — where prosumers (producers + consumers) can monetise their excess solar generation and buy clean energy directly from their neighbours.
          </p>
          <div style={{ display:'flex', gap:10 }}>
            <NavLink to="/marketplace" className="btn btn-ink">
              Open Market <ArrowRight size={14}/>
            </NavLink>
            <NavLink to="/help" className="btn btn-outline">How It Works</NavLink>
          </div>
        </div>

        {/* Divider headline */}
        <div style={{ display:'flex', alignItems:'center', gap:16, marginBottom:20 }}>
          <div style={{ flex:1, height:1, background:'var(--ink-rule)' }}/>
          <div className="section-eyebrow">Core Pillars</div>
          <div style={{ flex:1, height:1, background:'var(--ink-rule)' }}/>
        </div>

        {/* Pillars bento */}
        <div className="bento fu d1"
          style={{ gridTemplateColumns:'1fr 1fr', gridTemplateRows:'auto auto', marginBottom:48 }}>
          {PILLARS.map(({ icon:Icon, color, bg, title, body }, i) => (
            <div key={i} className="bento-cell" style={{
              background: bg, padding:'28px 28px',
              minHeight:180,
            }}>
              <div style={{ marginBottom:16 }}>
                <div style={{
                  width:38, height:38, borderRadius:10,
                  background:'rgba(255,255,255,0.18)',
                  display:'flex', alignItems:'center', justifyContent:'center', marginBottom:12
                }}>
                  <Icon size={20} color={
                    bg==='var(--lime)'    ? 'var(--on-lime)'   :
                    bg==='var(--mantis)' ? 'var(--on-mantis)' :
                    'var(--on-ink)'
                  }/>
                </div>
                <div style={{ fontFamily:'var(--display)', fontWeight:800, fontSize:18,
                  color: bg==='var(--lime)'    ? 'var(--on-lime)'   :
                         bg==='var(--mantis)' ? 'var(--on-mantis)' :
                         'var(--on-ink)',
                  marginBottom:8 }}>{title}</div>
                <p style={{ fontSize:14, lineHeight:1.7,
                  color: bg==='var(--lime)'    ? 'var(--on-lime-sub)'  :
                         bg==='var(--mantis)' ? 'var(--on-lime-sub)'  :
                         'var(--on-ink-sub)' }}>{body}</p>
              </div>
            </div>
          ))}
        </div>

        {/* Mission statement */}
        <div className="fu d2" style={{ background:'var(--ink)', borderRadius:'var(--r-xl)', padding:'36px 40px', marginBottom:48 }}>
          <div className="section-eyebrow" style={{ color:'var(--on-ink-sub)', marginBottom:12 }}>Our Mission</div>
          <blockquote style={{ fontFamily:'var(--display)', fontWeight:800, fontSize:28, color:'var(--on-ink)', lineHeight:1.2, letterSpacing:'-0.02em', maxWidth:700, marginBottom:16 }}>
            "A world where every rooftop battery and solar panel can participate in a fair, open energy economy."
          </blockquote>
          <p style={{ fontSize:15, color:'var(--on-ink-sub)', lineHeight:1.7, maxWidth:580 }}>
            GridLedger is built as an open-source reference implementation. All contracts are verified on Etherscan, all source code is on GitHub. There are no tokens for sale, no ICO, no investors. Just infrastructure for the future grid.
          </p>
        </div>

        {/* Tech stack */}
        <div className="fu d3">
          <div className="section-eyebrow" style={{ marginBottom:16 }}>Technology Stack</div>
          <div className="seamless-grid seamless-grid-4" style={{ gridTemplateColumns:'repeat(4,1fr)' }}>
            {STACK.map(({ cat, items }) => (
              <div key={cat} className="sg-cell">
                <div style={{ fontFamily:'var(--display)', fontWeight:700, fontSize:13, marginBottom:12 }}>{cat}</div>
                <ul style={{ listStyle:'none', display:'flex', flexDirection:'column', gap:6 }}>
                  {items.map(item => (
                    <li key={item} style={{ fontSize:13, color:'var(--ink-dim)', display:'flex', alignItems:'flex-start', gap:6 }}>
                      <span style={{ color:'var(--forest)', fontSize:10, marginTop:3, flexShrink:0 }}>▸</span>{item}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>

      </div>
    </div>
  )
}
